#!/usr/bin/env python3
"""
compile_profile.py — frequency plan compiler for ConnexInsights sub-GHz targets.

Reads:
  legal_profile.json        — zone definitions and hardware bounds
  digital_tv_exclusion.json — DTV channel exclusion ranges (with guard bands)

Writes to <out_dir> (default: ../../src/generated/):
  rf_zone_table.h       — C header included by RFProfile.cpp at compile time
  rf_profile_manifest.json — human-readable summary of what was generated
  exclusion_mask.bin    — 1-byte-per-MHz bitmask (bit 0 = excluded), 151–959 MHz
  build_flags.txt       — -DRF_PROFILE_CONFIG_HASH=0x... for PlatformIO extra_flags

Usage:
  python compile_profile.py [--profile legal_profile.json]
                             [--exclusion digital_tv_exclusion.json]
                             [--out ../../src/generated]
                             [--dry-run]

Exit codes: 0 = success, 1 = validation error, 2 = I/O error
"""

import argparse
import hashlib
import json
import os
import struct
import sys
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
SCRIPT_DIR   = Path(__file__).resolve().parent
DEFAULT_PROFILE   = SCRIPT_DIR / "legal_profile.json"
DEFAULT_EXCLUSION = SCRIPT_DIR / "digital_tv_exclusion.json"
DEFAULT_OUT       = SCRIPT_DIR / "../../src/generated"

HW_MIN_MHZ = 151
HW_MAX_MHZ = 959


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def die(msg: str, code: int = 1) -> None:
    sys.stderr.write(f"ERROR: {msg}\n")
    sys.exit(code)


def load_json(path: Path) -> dict:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        die(f"File not found: {path}", 2)
    except json.JSONDecodeError as e:
        die(f"JSON parse error in {path}: {e}", 2)


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------
def build_exclusion_set(exclusion_data: dict) -> set:
    """Return set of MHz integers that are excluded (within [HW_MIN_MHZ, HW_MAX_MHZ])."""
    excluded = set()
    for r in exclusion_data.get("exclusion_ranges", []):
        lo = int(r["lo_mhz"])
        hi = int(r["hi_mhz"])
        for mhz in range(lo, hi + 1):
            if HW_MIN_MHZ <= mhz <= HW_MAX_MHZ:
                excluded.add(mhz)
    return excluded


def zone_freqs(zone_def: dict, excluded: set) -> list:
    """Sorted list of allowed integer MHz values for a zone, after exclusion."""
    lo = int(zone_def["min_mhz"])
    hi = int(zone_def["max_mhz"])
    return sorted(
        mhz for mhz in range(max(lo, HW_MIN_MHZ), min(hi, HW_MAX_MHZ) + 1)
        if mhz not in excluded
    )


def compute_config_hash(profile_data: dict, exclusion_data: dict) -> str:
    """Deterministic SHA-256 of the normalised profile + exclusion inputs."""
    payload = json.dumps(
        {"profile": profile_data, "exclusion": exclusion_data},
        sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode()
    return hashlib.sha256(payload).hexdigest()


def build_exclusion_mask(excluded: set) -> bytes:
    """1 byte per MHz from HW_MIN_MHZ to HW_MAX_MHZ. Bit 0 = excluded."""
    size = HW_MAX_MHZ - HW_MIN_MHZ + 1
    mask = bytearray(size)
    for mhz in excluded:
        idx = mhz - HW_MIN_MHZ
        if 0 <= idx < size:
            mask[idx] = 1
    return bytes(mask)


def format_freq_array(arr_name: str, count_define: str, freqs: list, comment: str) -> str:
    vals = ", ".join(str(f) for f in freqs)
    return (
        f"/* {comment} */\n"
        f"static const uint16_t {arr_name}[] = {{{vals}}};\n"
        f"#define {count_define} {len(freqs)}U\n"
    )


def generate_header(profile_data: dict, freqs_by_zone: dict,
                    exclusion_ranges: list, config_hash_hex: str) -> str:
    legal_id  = profile_data["legal_profile_id"]
    version   = profile_data.get("legal_profile_version", "?")
    hash_u32  = int(config_hash_hex[:8], 16)

    lines = [
        "/* AUTO-GENERATED by frequency_plan_compiler — do not edit by hand */",
        f"/* Source: legal_profile + digital_tv_exclusion + 868/915 defaults  */",
        f"/* Config hash: {config_hash_hex} */",
        f"/* Legal profile: {legal_id} v{version} */",
        "",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"#define RF_PROFILE_CONFIG_HASH    0x{hash_u32:08X}UL",
        f'#define RF_PROFILE_LEGAL_ID       "{legal_id}"',
        f"#define RF_FREQ_MIN_MHZ           {HW_MIN_MHZ}U",
        f"#define RF_FREQ_MAX_MHZ           {HW_MAX_MHZ}U",
        "",
    ]

    zone_names = {
        "LOW":  ("rfZoneLowFreqs",  "RF_ZONE_LOW_FREQ_COUNT"),
        "MID":  ("rfZoneMidFreqs",  "RF_ZONE_MID_FREQ_COUNT"),
        "HIGH": ("rfZoneHighFreqs", "RF_ZONE_HIGH_FREQ_COUNT"),
    }
    for zone_key, (arr_name, count_define) in zone_names.items():
        freqs = freqs_by_zone.get(zone_key, [])
        lines.append(format_freq_array(
            arr_name, count_define, freqs,
            f"Zone {zone_key}: {len(freqs)} allowed frequencies"
        ))

    lines += [
        "/* Exclusion ranges */",
        "typedef struct { uint16_t lo_mhz; uint16_t hi_mhz; const char* reason; } ExclusionRange_t;",
        "static const ExclusionRange_t rfExclusionRanges[] = {",
    ]
    for r in exclusion_ranges:
        lo, hi, reason = int(r["lo_mhz"]), int(r["hi_mhz"]), r["reason"]
        lines.append(f'    {{ {lo:3d}, {hi:3d}, "{reason}" }},')
    lines += [
        "};",
        f"#define RF_EXCLUSION_RANGE_COUNT {len(exclusion_ranges)}U",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def generate_manifest(profile_data: dict, freqs_by_zone: dict,
                      exclusion_ranges: list, excluded: set,
                      config_hash_hex: str) -> dict:
    total_mhz = HW_MAX_MHZ - HW_MIN_MHZ + 1
    included  = total_mhz - len(excluded)
    zone_summary = {
        zone: {
            "count": len(f),
            "min":   min(f) if f else None,
            "max":   max(f) if f else None,
        }
        for zone, f in freqs_by_zone.items()
    }
    return {
        "config_hash":            config_hash_hex,
        "generated_at":           datetime.now(timezone.utc).isoformat(),
        "legal_profile_id":       profile_data["legal_profile_id"],
        "legal_profile_version":  profile_data.get("legal_profile_version", "?"),
        "guard_band_mhz":         profile_data.get("guard_band_mhz", 4),
        "hardware_min_mhz":       HW_MIN_MHZ,
        "hardware_max_mhz":       HW_MAX_MHZ,
        "2400_mhz_disabled":      True,
        "868_mhz_excluded":       any(864 <= r["lo_mhz"] <= 868 for r in exclusion_ranges),
        "915_mhz_excluded":       any(911 <= r["lo_mhz"] <= 915 for r in exclusion_ranges),
        "zone_summary":           zone_summary,
        "included_count":         included,
        "excluded_count":         len(excluded),
        "excluded_ranges":        exclusion_ranges,
        "warnings":               [],
    }


# ---------------------------------------------------------------------------
# Validate inputs
# ---------------------------------------------------------------------------
def validate_profile(profile_data: dict) -> None:
    required = ["legal_profile_id", "zones"]
    for key in required:
        if key not in profile_data:
            die(f"legal_profile.json missing required key: '{key}'")
    zones = profile_data["zones"]
    for name in ("LOW", "MID", "HIGH"):
        if name not in zones:
            die(f"legal_profile.json zones missing: '{name}'")
        zone = zones[name]
        for field in ("min_mhz", "max_mhz"):
            if field not in zone:
                die(f"Zone {name} missing field: '{field}'")
        if zone["min_mhz"] < HW_MIN_MHZ or zone["max_mhz"] > HW_MAX_MHZ:
            die(f"Zone {name} range {zone['min_mhz']}-{zone['max_mhz']} outside hardware limits {HW_MIN_MHZ}-{HW_MAX_MHZ}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description="ConnexInsights frequency plan compiler")
    parser.add_argument("--profile",   default=str(DEFAULT_PROFILE),   help="legal_profile.json path")
    parser.add_argument("--exclusion", default=str(DEFAULT_EXCLUSION),  help="digital_tv_exclusion.json path")
    parser.add_argument("--out",       default=str(DEFAULT_OUT),        help="Output directory")
    parser.add_argument("--dry-run",   action="store_true",             help="Print outputs without writing files")
    args = parser.parse_args()

    profile_path   = Path(args.profile).resolve()
    exclusion_path = Path(args.exclusion).resolve()
    out_dir        = Path(args.out).resolve()

    profile_data   = load_json(profile_path)
    exclusion_data = load_json(exclusion_path)

    validate_profile(profile_data)

    # Build frequency sets
    excluded = build_exclusion_set(exclusion_data)
    zones    = profile_data["zones"]
    freqs_by_zone = {
        "LOW":  zone_freqs(zones["LOW"],  excluded),
        "MID":  zone_freqs(zones["MID"],  excluded),
        "HIGH": zone_freqs(zones["HIGH"], excluded),
    }

    # Validate: each zone must have at least 4 frequencies
    for name, freqs in freqs_by_zone.items():
        if len(freqs) < 4:
            die(f"Zone {name} has only {len(freqs)} allowed frequencies — check exclusion ranges")

    config_hash_hex     = compute_config_hash(profile_data, exclusion_data)
    exclusion_ranges    = exclusion_data.get("exclusion_ranges", [])
    header_content      = generate_header(profile_data, freqs_by_zone, exclusion_ranges, config_hash_hex)
    manifest            = generate_manifest(profile_data, freqs_by_zone, exclusion_ranges, excluded, config_hash_hex)
    mask_bytes          = build_exclusion_mask(excluded)
    hash_u32            = int(config_hash_hex[:8], 16)
    build_flags_content = f"-DRF_PROFILE_CONFIG_HASH=0x{hash_u32:08X}UL\n"

    # Summary
    print(f"Legal profile:  {profile_data['legal_profile_id']}")
    print(f"Config hash:    {config_hash_hex[:16]}...")
    for zone, freqs in freqs_by_zone.items():
        print(f"  Zone {zone}: {len(freqs):4d} frequencies")
    print(f"  Excluded MHz: {len(excluded)}")
    print(f"  Exclusion ranges: {len(exclusion_ranges)}")

    if args.dry_run:
        print("\n[dry-run] No files written.")
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "rf_zone_table.h").write_text(header_content, encoding="utf-8")
    (out_dir / "rf_profile_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=True), encoding="utf-8"
    )
    (out_dir / "exclusion_mask.bin").write_bytes(mask_bytes)
    (out_dir / "build_flags.txt").write_text(build_flags_content, encoding="utf-8")

    print(f"\nWrote to {out_dir}/")
    print(f"  rf_zone_table.h")
    print(f"  rf_profile_manifest.json")
    print(f"  exclusion_mask.bin  ({len(mask_bytes)} bytes)")
    print(f"  build_flags.txt     ({build_flags_content.strip()})")


if __name__ == "__main__":
    main()
